/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CatalogDotjsonRouteImport } from './routes/catalog[.]json'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as RawProductsSplatRouteImport } from './routes/raw.products.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogDotjsonRoute = CatalogDotjsonRouteImport.update({
  id: '/catalog.json',
  path: '/catalog.json',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RawProductsSplatRoute = RawProductsSplatRouteImport.update({
  id: '/raw/products/$',
  path: '/raw/products/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/catalog.json': typeof CatalogDotjsonRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/problems': typeof ProblemsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/raw/products/$': typeof RawProductsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/catalog.json': typeof CatalogDotjsonRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/problems': typeof ProblemsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/raw/products/$': typeof RawProductsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/catalog.json': typeof CatalogDotjsonRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/problems': typeof ProblemsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/raw/products/$': typeof RawProductsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/catalog.json'
    | '/knowledge'
    | '/llms.txt'
    | '/problems'
    | '/shop'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/raw/products/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/catalog.json'
    | '/knowledge'
    | '/llms.txt'
    | '/problems'
    | '/shop'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/raw/products/$'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/catalog.json'
    | '/knowledge'
    | '/llms.txt'
    | '/problems'
    | '/shop'
    | '/sitemap.xml'
    | '/products/$slug'
    | '/raw/products/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CatalogDotjsonRoute: typeof CatalogDotjsonRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProblemsRoute: typeof ProblemsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  RawProductsSplatRoute: typeof RawProductsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog.json': {
      id: '/catalog.json'
      path: '/catalog.json'
      fullPath: '/catalog.json'
      preLoaderRoute: typeof CatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/products/$': {
      id: '/raw/products/$'
      path: '/raw/products/$'
      fullPath: '/raw/products/$'
      preLoaderRoute: typeof RawProductsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CatalogDotjsonRoute: CatalogDotjsonRoute,
  KnowledgeRoute: KnowledgeRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProblemsRoute: ProblemsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  RawProductsSplatRoute: RawProductsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}